/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package content_kasir;

import inc.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fadli Abdan Syakur
 */
public class data_pasok extends javax.swing.JInternalFrame {

    Connection conn;
    Statement st;
    ResultSet rs;
    
    int idBuku, idDist;
    
    
    private void tampil(){
         DefaultTableModel model= new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Distributor");
        model.addColumn("Judul Buku");
        model.addColumn("Jumlah");
        model.addColumn("Tanggal");
        try{
            String sql="select pasok.id_pasok, distributor.nama_distributor, buku.judul, pasok.jumlah, pasok.tanggal from pasok, distributor, buku where distributor.id_distributor=pasok.id_distributor and buku.id_buku=pasok.id_buku";
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            
            int no=0;
            while(rs.next()){
                no++;
                model.addRow(new Object[]{
                    no, rs.getString("id_pasok"), rs.getString("nama_distributor"), rs.getString("judul"), rs.getString("jumlah"), rs.getString("tanggal")
                });
            }tData.setModel(model);
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void bersih(){
        tId.setText("");
        cDist.setSelectedIndex(0);
        cBuku.setSelectedIndex(0);
        tJumlah.setText("");
    }
    /**
     * Creates new form data_pasok
     */
    public data_pasok() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cBuku = new javax.swing.JComboBox<>();
        bSimpan = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        tId = new javax.swing.JTextField();
        bHapus = new javax.swing.JButton();
        tJumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bUbah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cDist = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\windows\\Downloads\\icons8-reading-64.png")); // NOI18N
        jLabel1.setText("Transaksi Buku Masuk");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));

        jLabel2.setText("ID");

        jLabel3.setText("Distributor");

        cBuku.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cBukuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBukuActionPerformed(evt);
            }
        });

        bSimpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\windows\\Downloads\\icons8-save-as-10.png")); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\windows\\Downloads\\icons8-synchronize-filled-10.png")); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bHapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\windows\\Downloads\\icons8-trash-10.png")); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        jLabel4.setText("Buku");

        bUbah.setIcon(new javax.swing.ImageIcon("C:\\Users\\windows\\Downloads\\icons8-edit-property-10 (1).png")); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        jLabel5.setText("Jumlah");

        cDist.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cDistPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(57, 57, 57)
                        .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cDist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSimpan)
                                    .addComponent(bHapus))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bReset)
                                    .addComponent(bUbah))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bUbah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHapus)
                    .addComponent(bReset))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tData);

        jLabel6.setText("Pencarian");

        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tCari)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql1= "insert into pasok values(NULL, '"+idDist+"', '"+idBuku+"', '"+tJumlah.getText()+"', now());";
            conn= config.Conn();
            st= conn.createStatement();
            st.executeUpdate(sql1);
            tampil();
            bersih();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try{
            String sql= "select * from distributor";
            conn= config.Conn();
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            while (rs.next()){
                cDist.addItem(rs.getString("nama_distributor"));
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
         try{
            String sql= "select * from buku";
            conn= config.Conn();
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            while (rs.next()){
                cBuku.addItem(rs.getString("judul"));
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
         tampil();
    }//GEN-LAST:event_formInternalFrameOpened
        
    private void cDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDistActionPerformed
        // TODO add your handling code here:
//        try{
//            String sql= "select * from distributor where nama_distributor='"+cDist.getSelectedItem()+"'";
//            conn= config.Conn();
//            st= conn.createStatement();
//            rs= st.executeQuery(sql);
//            if (rs.next()){
//                idDist= rs.getInt("id_distributor");
//            }
//        }catch (Exception e){
//            System.out.println(e.getMessage());
//        }
    }//GEN-LAST:event_cDistActionPerformed

    private void cBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBukuActionPerformed
        // TODO add your handling code here:
//        try{
//            String sql= "select * from buku where judul='"+cBuku.getSelectedItem()+"'";
//            conn= config.Conn();
//            st= conn.createStatement();
//            rs= st.executeQuery(sql);
//            if (rs.next()){
//                idBuku= rs.getInt("id_buku");
//            }
//        }catch (Exception e){
//            System.out.println(e.getMessage());
//        }
    }//GEN-LAST:event_cBukuActionPerformed

    private void cDistPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cDistPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try{
            String sql= "select * from distributor where nama_distributor='"+cDist.getSelectedItem()+"'";
            conn= config.Conn();
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            if (rs.next()){
                idDist= rs.getInt("id_distributor");
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cDistPopupMenuWillBecomeInvisible

    private void cBukuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBukuPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try{
            String sql= "select * from buku where judul='"+cBuku.getSelectedItem()+"'";
            conn= config.Conn();
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            if (rs.next()){
                idBuku= rs.getInt("id_buku");
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cBukuPopupMenuWillBecomeInvisible

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_bResetActionPerformed

    private void tDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDataMouseClicked
        // TODO add your handling code here:
        int baris= tData.getSelectedRow();
        tId.setText(tData.getModel().getValueAt(baris, 1).toString());
        cDist.setSelectedItem(tData.getModel().getValueAt(baris, 2).toString());
        cBuku.setSelectedItem(tData.getModel().getValueAt(baris, 3).toString());
        tJumlah.setText(tData.getModel().getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tDataMouseClicked

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        try{
            String sql= "select * from buku where judul='"+cBuku.getSelectedItem()+"'";
            conn= config.Conn();
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            if (rs.next()){
                idBuku= rs.getInt("id_buku");
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
        try{
            String sql= "select * from distributor where nama_distributor='"+cDist.getSelectedItem()+"'";
            conn= config.Conn();
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            if (rs.next()){
                idDist= rs.getInt("id_distributor");
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
        
        try{
            String sql= "update pasok set id_distributor='"+idDist+"', id_buku='"+idBuku+"', jumlah='"+tJumlah.getText()+"', tanggal=now() where id_pasok='"+tId.getText()+"'";
            conn= config.Conn();
            st= conn.createStatement();
            st.executeUpdate(sql);
            tampil();
            bersih();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql= "delete from pasok where id_pasok='"+tId.getText()+"'";
            conn= config.Conn();
            st= conn.createStatement();
            st.executeUpdate(sql);
            tampil();
            bersih();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Distributor");
        model.addColumn("Judul Buku");
        model.addColumn("Jumlah");
        model.addColumn("Tanggal");
        try{
            String sql="select pasok.id_pasok, distributor.nama_distributor, buku.judul, pasok.jumlah, pasok.tanggal from pasok, distributor, buku where distributor.id_distributor=pasok.id_distributor and buku.id_buku=pasok.id_buku and(pasok.id_pasok like '%"+tCari.getText()+"%' or distributor.nama_distributor like '%"+tCari.getText()+"%' or buku.judul like '%"+tCari.getText()+"%' or pasok.jumlah like '%"+tCari.getText()+"%' or pasok.tanggal like '%"+tCari.getText()+"%')";
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            
            int no=0;
            while(rs.next()){
                no++;
                model.addRow(new Object[]{
                    no, rs.getString("id_pasok"), rs.getString("nama_distributor"), rs.getString("judul"), rs.getString("jumlah"), rs.getString("tanggal")
                });
            }tData.setModel(model);
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cBuku;
    private javax.swing.JComboBox<String> cDist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tData;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tJumlah;
    // End of variables declaration//GEN-END:variables
}
